---
topic: "water"
title: "Trends in Stream and River Flow"
output: 
  pdf_document: envreportutils.internal::print_ver
  html_document:
    self_contained: false
editor_options: 
  chunk_output_type: console
---

```{=html}
<!--
Copyright 2022 Province of British Columbia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
-->
```

```{r setup, echo=FALSE, cache=FALSE, warning=FALSE, message=FALSE}

library(envreportutils)
library(tidyhydat)
library(sf)
library(EnvStats)
library(data.table)
library(tidyverse)
library(ggtext)
library(ggrepel)
library(patchwork)
library(ggpubr)
library(knitr)

opts_chunk$set(echo=FALSE, cache=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.height=3.5, fig.width = 8, fig.align = 'center')


theme_print <-   theme(axis.text.y = element_text(size = 8),
                       axis.text.x = element_text(size = 8),
                       axis.title.y = element_text(size = 10,
                                                   margin = margin(t = 0, r = 10,
                                                                   b = 0, l = 0,
                                                                   unit = "pt")),
                       plot.title = element_text(size = 10, hjust = 0.5),
                       plot.margin = unit(c(6,6,6,2),"mm"))

#theme for plots with integrated labels
theme_summary <- theme(axis.text.y = element_text(size = 8),
                       axis.text.x = element_text(size = 8),
                       axis.title.y = element_text(size = 10,
                                                   margin = margin(t = 0, r = 10,
                                                                   b = 0, l = 0,
                                                                   unit = "pt")),
                       plot.title = element_text(size = 10, hjust = 0.5),
                       plot.margin = unit(c(0.5,3.5,0.5,0.5), "cm"))

is_html <- knitr::is_html_output()
is_pdf <- knitr::is_latex_output()

# if (!id_pdf) opts_knit$set(base.dir = str_remove(here(),"print_ver"))
if (is_pdf) opts_chunk$set(fig.width = 6.5)
if (is_pdf) opts_chunk$set(fig.height = 3.5)

mypal = 'Dark2'

# Load in data.
flow_dat = read.csv('app/www/flow_dat.csv') %>% 
  as_tibble()
```

```{r set_up_example_station_data}
example_station = flow_dat %>% 
  add_count(STATION_NUMBER) %>% 
  arrange(desc(n)) %>% 
  slice(1) %>% 
  pull(STATION_NUMBER)

example_station_name = hy_stations(station_number = example_station) %>% pull(STATION_NAME)

stdat = flow_dat %>% filter(STATION_NUMBER == example_station)

number_records_per_year = hy_daily_flows(station_number = example_station) %>% 
  mutate(Year = year(Date)) %>% 
  count(Year, name = 'days_with_data') %>% 
  #Correct for leap years. For simplicity's sake, make those years look like 365 days of data.
  mutate(days_with_data = replace(days_with_data, days_with_data > 365, 365)) %>% 
  mutate(without_data = 365 - days_with_data)
```

### Example Station: `r str_to_title(example_station_name)` (`r example_station`)

#### Data Distribution through Time
```{r data_histogram_of_time, fig.width=12}
dat_hist = number_records_per_year %>% 
  pivot_longer(cols = c(days_with_data,without_data), names_to = 'variable', values_to = 'value') %>% 
  # Visually clean up top of figure.
  filter(value != 0) %>% 
  mutate(variable = ifelse(variable == 'without_data','No Data','Data')) %>% 
  mutate(variable = factor(variable, levels = c('No Data','Data'))) %>% 
  ggplot() +
  geom_col(aes(x = Year, y = value, fill = variable, col = variable), 
           position = 'stack') + 
  scale_fill_brewer(palette = mypal, direction = -1) + 
  scale_color_brewer(palette = mypal, direction = -1) +
  scale_x_continuous(breaks = scales::breaks_pretty(n = 10)) +
  scale_y_continuous(breaks = scales::breaks_pretty(n = 10),
                     sec.axis = sec_axis( trans=~./365, 
                                          labels = scales::percent_format(),
                                          name="Percentage")
                     ) +
  labs(y = "Days in Year with Data",
       fill = 'Data Availability',
       col = 'Data Availability') +
  theme(legend.position = 'none') + 
  ggthemes::theme_few()
  
dat_hist
```

```{r add_mk_trend_test_results}
longdat = stdat %>% 
  pivot_longer(cols = c(Mean,Median,DoY_50pct_TotalQ,
                        Min_7_Day,Min_7_Day_DoY,Total_Volume_m3),
               names_to = 'variable', values_to = 'values') %>% 
  mutate(variable = case_when(
    variable == 'Min_7_Day' ~ '7-Day Low Flow',
    variable == 'Min_7_Day_DoY' ~ '7-Day Low Flow Day of Year',
    variable == 'DoY_50pct_TotalQ' ~ 'Day of 50% Annual Flow',
    variable == 'Total_Volume_m3' ~ 'Total Volume (m<sup>3</sup>)',
    T ~ variable
  )) %>% 
  group_by(Year) %>% 
  arrange(variable) %>% 
  ungroup()
  
# Adjust Day-of-Year values to reflect cyclical nature of year.
longdat = longdat %>% 
  mutate(values = case_when(
    variable %in% c('Day of 50% Annual Flow','7-Day Low Flow Day of Year') ~ abs(values-182),
    T ~ values
  ))

date_vars = c('7-Day Low Flow Day of Year','Day of 50% Annual Flow')

mannkendall_results = longdat %>% 
  group_by(variable) %>% 
  reframe(MK_results = kendallTrendTest(values ~ Year)[c('statistic','p.value','estimate')]) %>%
  unnest(MK_results) %>%
  unnest_longer(col = MK_results) %>%
  cbind(MK_names = c('Statistic','P_value','Tau','Slope','Intercept')) %>% 
  dplyr::select(-MK_results_id) %>% 
  pivot_wider(names_from = MK_names, values_from = MK_results) %>% 
  #Add in the stations that had too few points to plot.
  mutate(trend_sig_short = fcase(
    abs(Tau) <= 0.05, "no trend",
    Tau < -0.05 & P_value < 0.05, "sig trend neg",
    Tau < -0.05 & P_value >= 0.05, "nonsig trend neg",
    Tau > 0.05 & P_value >= 0.05, "nonsig trend pos",
    Tau > 0.05 & P_value < 0.05 , "sig trend pos"
  )) %>% 
  mutate(trend_sig = fcase(
    abs(Tau) <= 0.05, "No Trend",
    Tau < -0.05 & P_value < 0.05 & variable %in% date_vars, "Significant Trend Earlier",
    Tau < -0.05 & P_value >= 0.05 & variable %in% date_vars, "Non-Significant Trend Earlier",
    Tau > 0.05 & P_value >= 0.05 & variable %in% date_vars, "Non-Significant Trend Later",
    Tau > 0.05 & P_value < 0.05 & variable %in% date_vars, "Significant Trend Later",
    Tau < -0.05 & P_value < 0.05, "Significant Trend Down",
    Tau < -0.05 & P_value >= 0.05, "Non-Significant Trend Down",
    Tau > 0.05 & P_value >= 0.05, "Non-Significant Trend Up",
    Tau > 0.05 & P_value < 0.05, "Significant Trend Up"
  ))

plotdat = longdat %>% 
  left_join(mannkendall_results) %>% 
  mutate(pred.y = Intercept + Slope*Year) %>% 
  dplyr::select(Year:values,pred.y,P_value,trend_sig,trend_sig_short)
```

### Metric Plots

```{r define_plotting_function_for_flow_metrics}
plot_function = function(data, chosen_var){
  data %>% 
    filter(variable == chosen_var) %>% 
    ggplot(aes(x=Year)) +
    geom_point(aes(y=values)) +
    geom_line(aes(y=pred.y,color=trend_sig_short),
              linetype = 1,
              linewidth = 2,
              alpha = 0.75) + 
    labs(colour = 'Trend Significance') +
    scale_colour_manual(values = c("sig trend pos" = "#49A0F9",
                                   "nonsig trend pos" = "lightblue",
                                   "no trend" = "grey",
                                   'nonsig trend neg' = "#F7C962",
                                   'sig trend neg' = '#F75C41'
                                   ),
                        limits = c("sig trend pos","nonsig trend pos","no trend","nonsig trend neg","sig trend neg"),
                        labels = c("Sig. Pos.","Nonsig. Pos.","None","Nonsig. Neg.","Sig. Neg.")) +
    labs(#title = chosen_var,
         y = chosen_var) + 
    theme_minimal() +
    theme(plot.title = ggtext::element_markdown(),
          axis.title.y = ggtext::element_markdown())
}
```

### Flow Levels

```{r plot_and_combine_metrics}
a = plot_function(plotdat, chosen_var = 'Mean')
b = plot_function(plotdat, chosen_var = 'Median')
c = plot_function(plotdat, chosen_var = 'Total Volume (m<sup>3</sup>)')
d = plot_function(plotdat, chosen_var = '7-Day Low Flow') 

ggarrange(a,b,c,d,
                  ncol=2,nrow=2,
                  common.legend = T, legend = 'bottom')
```

### Flow Event Dates

```{r day_of_year_half_flow_scatter}
half_flow_doy_scatter = plotdat %>%
  filter(variable == 'Day of 50% Annual Flow') %>% 
  ggplot() +
  geom_point(aes(x=Year,y=values)) +
  geom_line(aes(x=Year,y=pred.y,col = trend_sig_short),
            linetype = 1,
            linewidth = 2,
            alpha = 0.75) + 
  labs(y = 'Days from Start/End of Year') + 
  scale_y_continuous(breaks = scales::breaks_pretty(n = 6)) + 
  labs(colour = 'Trend Significance') +
    scale_colour_manual(values = c("sig trend pos" = "#49A0F9",
                                   "nonsig trend pos" = "lightblue",
                                   "no trend" = "grey",
                                   'nonsig trend neg' = "#F7C962",
                                   'sig trend neg' = '#F75C41'
                                   ),
                        limits = c("sig trend pos","nonsig trend pos","no trend","nonsig trend neg","sig trend neg"),
                        labels = c("Sig. Pos.","Nonsig. Pos.","None","Nonsig. Neg.","Sig. Neg.")) +
  theme_minimal() + 
  theme(legend.position = 'bottom')

text_label_dat = data.frame(Year = seq(1900,2025,25)) %>% 
  mutate(values_plus = 250,
         Year_char = as.character(Year))

season_labels = data.frame(seasons = c(80,171,265,355),
                           labels = c("Vernal\nEquinox",
                                      "Summer\nSolstice",
                                      "Autumnal\nEquinox",
                                      "Winter\nSolstice")) %>% 
  mutate(x = 2030)

half_flow_circle_plot_by_year = plotdat %>%
  filter(variable == 'Day of 50% Annual Flow') %>% 
  ggplot(aes(x=Year,y=values)) +
  geom_point(aes(col = Year)) +
  geom_line(aes(col = Year)) +
  geom_smooth() +
  geom_text(aes(x = Year, y = values_plus, label = Year),
            col = 'white',
            data = text_label_dat) +
  geom_text(aes(x = x, y = seasons, label = labels),
            col = 'white',
            data = season_labels) +
  labs(y = '50% Annual Flow Discharge Day of Year', x = "") +
  scale_y_continuous(limits = c(0, 365),
                     breaks = c(0,100,200,300),
                     labels = paste0('Day ',c('365/0','100','200','300'))
                     ) +
  scale_x_continuous(limits = c(1900, 2030), 
                     breaks = seq(1900,2025,25)) +
  coord_polar(theta = 'y') +
  scale_color_distiller(palette = 'Spectral',
                        limits = c(1900,2025),
                        breaks = seq(1900,2025,25),
                        guide = guide_legend(
                          barheight = 10,
                          legend.key = element_rect(fill = 'white')
                        )
                        ) +
  scale_fill_distiller(palette = 'Spectral', guide = 'legend') +
  theme_dark() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(colour = 'white'),
        axis.title = element_text(size = 16),
        legend.title = ggtext::element_markdown(),
        legend.key = element_rect(fill = '#1e1e2f'),
        panel.background = element_rect(fill = '#1e1e2f'))
```

```{r}
half_flow_circle_plot_by_value = plotdat %>%
  filter(variable == 'Day of 50% Annual Flow') %>% 
  ggplot(aes(x=Year,y=values)) +
  geom_point(aes(col = values)) +
  geom_line(aes(col = values)) +
  geom_smooth() +
  geom_text(aes(x = Year, y = values_plus, label = Year),
            col = 'white',
            data = text_label_dat) +
  geom_text(aes(x = x, y = seasons, label = labels),
            col = 'white',
            data = season_labels) +
  labs(y = '50% Annual Flow Discharge Day of Year', x = "") +
  scale_y_continuous(limits = c(0, 365),
                     breaks = c(0,100,200,300),
                     labels = paste0('Day ',c('365/0','100','200','300'))
                     ) +
  scale_x_continuous(limits = c(1900, 2030), 
                     breaks = seq(1900,2025,25)) +
  coord_polar(theta = 'y') +
  scale_color_distiller(palette = 'Spectral') +
  labs(col = 'Days from <br>Year Start/End') +
  scale_fill_distiller(palette = 'Spectral', guide = 'legend') +
  theme_dark() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(colour = 'white'),
        # axis.title = element_text(size = 16),
        legend.title = ggtext::element_markdown(),
        legend.key = element_rect(fill = '#1e1e2f'),
        legend.position = 'none',
        panel.background = element_rect(fill = '#1e1e2f'))
```

```{r}
seven_day_lowflow_doy_scatter = plotdat %>%
  filter(variable == '7-Day Low Flow Day of Year') %>% 
  ggplot() +
  geom_point(aes(x=Year,y=values)) +
  geom_line(aes(x=Year,y=pred.y,col = trend_sig_short),
            linetype = 1,
            linewidth = 2,
            alpha = 0.75) + 
  labs(y = 'Days from Start/End of Year') + 
  scale_y_continuous(breaks = scales::breaks_pretty(n = 6)) + 
  labs(colour = 'Trend Significance') +
    scale_colour_manual(values = c("sig trend pos" = "#49A0F9",
                                   "nonsig trend pos" = "lightblue",
                                   "no trend" = "grey",
                                   'nonsig trend neg' = "#F7C962",
                                   'sig trend neg' = '#F75C41'
                                   ),
                        limits = c("sig trend pos","nonsig trend pos","no trend","nonsig trend neg","sig trend neg"),
                        labels = c("Sig. Pos.","Nonsig. Pos.","None","Nonsig. Neg.","Sig. Neg.")) +
  theme_minimal() + 
  theme(legend.position = 'bottom')
```

```{r}
seven_day_lowflow_doy_circle = plotdat %>%
  filter(variable == '7-Day Low Flow Day of Year') %>% 
  ggplot(aes(x=Year,y=values)) +
  geom_point(aes(col = Year)) +
  geom_text(aes(x = Year, y = values_plus, label = Year),
            col = 'white',
            data = text_label_dat) +
  geom_text(aes(x = x, y = seasons, label = labels),
            col = 'white',
            data = season_labels) +
  labs(y = '7-Day Low Flow Day of Year', x = "") +
  scale_y_continuous(limits = c(0, 365),
                     breaks = c(0,100,200,300),
                     labels = paste0('Day ',c('366/1','100','200','300'))
                     ) +
  scale_x_continuous(limits = c(1900, 2030), 
                     breaks = seq(1900,2025,25)) +
  coord_polar(theta = 'y') +
  scale_color_distiller(palette = 'Spectral', 
                        limits = c(1900,2025),
                        breaks = seq(1900,2025,25),
                        # labels = seq(1900,2025,25),
                        # guide = guide_legend(
                        #   override.aes = list(size = 3,
                        #                       breaks = seq(1900,2020,20))
                        guide = guide_legend(
                          barheight = 10,
                          legend.key = element_rect(fill = 'white')
                        )
                        ) + 
  scale_fill_distiller(palette = 'Spectral', guide = 'legend') +
  theme_dark() +
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.x = element_text(colour = 'white'),
        # axis.title = element_text(size = 16),
        legend.key = element_rect(fill = '#1e1e2f'),
        legend.position = 'none',
        panel.background = element_rect(fill = '#1e1e2f'))

```

#### Day of Year of 50% Annual Flow

```{r date_plots_half_flow}
ggarrange(
    half_flow_doy_scatter,
    half_flow_circle_plot_by_value,
    nrow = 1, ncol = 2)
```

#### Day of Year of 7-Day Mean Low Flow

```{r date_plots_seven_day_low_flow}
ggarrange(
    seven_day_lowflow_doy_scatter,
    seven_day_lowflow_doy_circle,
    nrow = 1, ncol = 2)
```

```{r animated_circle_plot}
# library(gganimate)
# anim_plot = plotdat %>%
#   filter(variable == 'Day of 50% Annual Flow') %>%
#   mutate(data_grouper = 'present') %>%
#   bind_rows(data.frame(Year = 1970, values = 10, STATION_NUMBER = '08NA002', data_grouper="missing")) %>%
#   ggplot(aes(x=Year,y=values)) +
#   geom_point(aes(col = data_grouper, group = data_grouper)) +
#   geom_line(aes(col = data_grouper, group = data_grouper)) +
#   # geom_smooth() +
#   geom_text(aes(x = as.numeric(Year_char), y = values_plus, label = Year_char),
#             col = 'white',
#             data = text_label_dat) +
#   geom_text(aes(x = x, y = seasons, label = labels),
#             col = 'white',
#             data = season_labels) +
#   labs(y = '50% Annual Flow Discharge Day of Year', x = "") +
#   scale_y_continuous(limits = c(0, 365),
#                      breaks = c(0,100,200,300),
#                      labels = paste0('Day ',c('365/0','100','200','300'))
#                      ) +
#   scale_x_continuous(limits = c(1900, 2030),
#                      breaks = seq(1900,2025,25)) +
#   coord_polar(theta = 'y') +
#   scale_color_manual(values = c('#1e1e2f','white')) +
#   theme_dark() +
#   theme(axis.text.y = element_blank(),
#         axis.ticks.y = element_blank(),
#         axis.text.x = element_text(colour = 'white'),
#         axis.title = element_text(size = 16),
#         legend.key = element_rect(fill = '#1e1e2f'),
#         panel.background = element_rect(fill = '#1e1e2f'),
#         legend.position = 'none')
# 
# annual_flow_trace = anim_plot +
#   transition_reveal(Year)
# 
# annual_flow_trace

# if(!file.exists('out/half_annual_flow_day_of_year_animation.gif')){
# gganimate::anim_save(filename = 'out/half_annual_flow_day_of_year_animation.gif',
#                      animation = annual_flow_trace)
# }
```
## Data

\*By accessing these datasets, you agree to the licence associated with each file, as indicated below.


------------------------------------------------------------------------

\newpage

