---
topic: "water"
title: "Trends in Stream and River Flow"
output: 
  html_document:
    self_contained: false
  pdf_document: envreportutils.internal::print_ver
editor_options: 
  chunk_output_type: console
---

```{=html}
<!--
Copyright 2022 Province of British Columbia

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
-->
```

```{r setup, echo=FALSE, cache=FALSE, warning=FALSE, message=FALSE}

library(envreportutils)
library(tidyhydat)
library(sf)
library(EnvStats)
library(data.table)
library(tidyverse)
library(ggtext)
library(ggrepel)
library(patchwork)
library(ggpubr)
library(knitr)

opts_chunk$set(echo=FALSE, cache=FALSE, warning=FALSE, message=FALSE, error=FALSE, fig.height=3.5, fig.width = 8, fig.align = 'center')


theme_print <-   theme(axis.text.y = element_text(size = 8),
                       axis.text.x = element_text(size = 8),
                       axis.title.y = element_text(size = 10,
                                                   margin = margin(t = 0, r = 10,
                                                                   b = 0, l = 0,
                                                                   unit = "pt")),
                       plot.title = element_text(size = 10, hjust = 0.5),
                       plot.margin = unit(c(6,6,6,2),"mm"))

#theme for plots with integrated labels
theme_summary <- theme(axis.text.y = element_text(size = 8),
                       axis.text.x = element_text(size = 8),
                       axis.title.y = element_text(size = 10,
                                                   margin = margin(t = 0, r = 10,
                                                                   b = 0, l = 0,
                                                                   unit = "pt")),
                       plot.title = element_text(size = 10, hjust = 0.5),
                       plot.margin = unit(c(0.5,3.5,0.5,0.5), "cm"))

is_html <- knitr::is_html_output()
is_pdf <- knitr::is_latex_output()

# if (!id_pdf) opts_knit$set(base.dir = str_remove(here(),"print_ver"))
if (is_pdf) opts_chunk$set(fig.width = 6.5)
if (is_pdf) opts_chunk$set(fig.height = 3.5)

mypal = 'Dark2'

bin_data_hist = T
bin_data_hist_size = 10

# Load in data.
flow_dat = read.csv('app/www/flow_dat.csv') %>% 
  as_tibble()

```

```{r}
flow_with_mk = flow_dat %>% 
  group_by(STATION_NUMBER) %>%
  reframe(MK_results = kendallTrendTest(values ~ Year)[c('statistic','p.value','estimate')]) %>%
  unnest(MK_results) %>%
  unnest_longer(col = MK_results) %>%
  group_by(STATION_NUMBER) %>%
  mutate(MK_results_id = c('Statistic','P_value','Tau','Slope','Intercept')) %>%
  pivot_wider(names_from = MK_results_id, values_from = MK_results) %>%
  mutate(trend_sig = fcase(
    abs(Tau) <= 0.05 , "No Trend",
    Tau < -0.05 & P_value < 0.05 & chosen_variable %in% c('DoY_50pct_TotalQ','Min_7_Day_DoY'), "Significant Trend Earlier",
    Tau < -0.05 & P_value >= 0.05 & chosen_variable %in% c('DoY_50pct_TotalQ','Min_7_Day_DoY'), "Non-Significant Trend Earlier",
    Tau > 0.05 & P_value >= 0.05 & chosen_variable %in% c('DoY_50pct_TotalQ','Min_7_Day_DoY'), "Non-Significant Trend Later",
    Tau > 0.05 & P_value < 0.05 & chosen_variable %in% c('DoY_50pct_TotalQ','Min_7_Day_DoY'), "Significant Trend Later",
    Tau < -0.05 & P_value < 0.05 & (!chosen_variable %in% c('DoY_50pct_TotalQ','Min_7_Day_DoY')), "Significant Trend Down",
    Tau < -0.05 & P_value >= 0.05 & (!chosen_variable %in% c('DoY_50pct_TotalQ','Min_7_Day_DoY')), "Non-Significant Trend Down",
    Tau > 0.05 & P_value >= 0.05 & (!chosen_variable %in% c('DoY_50pct_TotalQ','Min_7_Day_DoY')), "Non-Significant Trend Up",
    Tau > 0.05 & P_value < 0.05 & (!chosen_variable %in% c('DoY_50pct_TotalQ','Min_7_Day_DoY')), "Significant Trend Up"
  ))


```

## Data

\*By accessing these datasets, you agree to the licence associated with each file, as indicated below.


------------------------------------------------------------------------

\newpage

